### ISSUE TITLE
Issue when decode token with Unicode char.

### ISSUE THREAD

**Issue by thiensubs** [tomitribe/jwt-js-decode#12]
Dear @Dexmaster , @brunobat 
First at all, your library is very excited and helpful with me.

But when I using this library, it has issue about incorrect decode from token with unicode chars.

Such as, the correct chars is 'ủ' and your lib decode it to ' á»§'.   ....

I think it's  a small issue. But if it completed support unicode for all languages, this is my pleasure.

Because, I am not familiar with TypeScript, so i add a link with the correct decode (tested), maybe it helpful for you to turning this issue. https://stackoverflow.com/a/38552302/4631412

Regards,

**Comment by Dexmaster** [comment]
@thiensubs thank you for a positive reply.

Will look more into this issue in the beginning of November. I have additional plan how to refactor this library a bit and maybe add a bit of CI/CD automation for the future. So if you have any other issues or feel something missing please mention, or create additional issues for better visibility :)

**Comment by Dexmaster** [comment]
Fixed in version `1.7.0` https://www.npmjs.com/package/jwt-js-decode/v/1.7.0

**Comment by Dexmaster** [comment]
Closing it as fixed, we can re-open it if needed.
