### ISSUE TITLE
Using this library into angular project

### ISSUE THREAD

**Issue by jandrei** [tomitribe/jwt-js-decode#2]
Hello, how I can use this lib into angular project?

**Comment by Dexmaster** [comment]
Hello, here is one of use-cases of this library with latest Andgular. 
https://github.com/tomitribe/oauth2-jwt-angular
e.g.
https://github.com/tomitribe/oauth2-jwt-angular/blob/master/src/main/angular-app/src/app/services/auth.service.ts#L194

P.S. It's the non-standard case as is based on index.jsp, for server, but it's pretty straightforward. If you need simplified version I can provide you with one.
```typescript
import { jwtDecode } from 'jwt-js-decode';
...
const accessToken = jwtDecode(access_token).payload;
```
