### ISSUE TITLE
Cannot Use: Can't resolve imported dependency "crypto"

### ISSUE THREAD

**Issue by douglasg14b** [tomitribe/jwt-js-decode#27]
It seems this is a built in NPM package? I'm unsure why it cannot be found through. Problem with this lib, or environment?

* NPM: `v8.1.2`
* Node: `v16.13.2`
* Webpack: `v5`

This seems to have happened after going from webpack `v4` -> `v5`?

![image](https://user-images.githubusercontent.com/1400380/185698730-2c55f28b-3408-4d24-9d4f-b35edc39d8c6.png)

**Comment by Dexmaster** [comment]
Hello @douglasg14b, 

I believe you are building for browser and not node.js, so you should add to top level of your `package.json`
```
"browser": {
    "crypto": false
}
```

It will use alternative.

**Comment by dblevins** [comment]
@Dexmaster we should update the readme

**Comment by douglasg14b** [comment]
testing now

**Comment by douglasg14b** [comment]
It works if I do:

1. `npm install --save-dev crypto-browserify`

And then in webpack config:

```
        cfg.resolve.fallback = {
            crypto: require.resolve('crypto-browserify')
        };
```

Also looks like another dependency wants `stream` as well, so same thing as above but for `stream-browserify` as well.

**Comment by Dexmaster** [comment]
@douglasg14b it doesn't need crypto, you could try
```
cfg.resolve.fallback = {
    crypto: false
};
```
but I will do a test with Webpack 5 to be sure.

**Comment by Dexmaster** [comment]
another option is just force it to use correct version ```import { jwtDecode } from 'jwt-js-decode/dist/jwt-js-decode.min.js';```

**Comment by Dexmaster** [comment]
@dblevins I will investigate this use case issue and will do a readme update.

**Comment by Dexmaster** [comment]
Ok tested with Webpack 5: https://stackblitz.com/edit/github-m1gvkd?file=src/index.js
1.4.1 works with Webpack 5 and
```
resolve: {
  fallback: {
    crypto: false,
  },
},
```
For now, will update Readme with Webpack 5 clause.

**Comment by Dexmaster** [comment]
Will investigate what they changed next week.

**Comment by douglasg14b** [comment]
@Dexmaster Thank you for such a quick response!!

I'm in the middle of another hairy migration task, but will revisit this once that's sorted.

**Comment by Dexmaster** [comment]
Ok I have:
- updated all dependencies
- checked tests (plus updated webCrypto as it's bundled into node crypto from node v15)
- added testing workflow (for PRs and master branch commits)
- done a version bump to 1.5.0
As far as I see, jwt-js-decode works perfectly fine on Webpack 5 with config change that I provided here and in readme:
```
resolve: {
  fallback: {
    crypto: false,
  },
},
```
I believe this is sufficient fix for this issue.

@douglasg14b If you don't have any more issue, I will be closing this one an opening enhancement issue (for Webpack 5) in next few days.

**Comment by douglasg14b** [comment]
@Dexmaster My bad, COVID brain has me forgetting about this. Thanks for the ping.

I am not having further complications, thank you for the investigation & information. It's appreciated.
