### ISSUE TITLE
Can't use? "TypeError: jwt_js_decode__WEBPACK_IMPORTED_MODULE_16__.default is undefined"

### ISSUE THREAD

**Issue by douglasg14b** [tomitribe/jwt-js-decode#4]
Added this to NPM, imported into file, and tried to call it, then received the following error:

`"TypeError: jwt_js_decode__WEBPACK_IMPORTED_MODULE_16__.default is undefined"`

This only occurs when using `import jwtJsDecode from 'jwt-js-decode';` using `const jwtJsDecode = require('jwt-js-decode');` works.

Any idea why?

**Comment by douglasg14b** [comment]
Had to use `import * as jwtJsDecode from 'jwt-js-decode';` instead

**Comment by Dexmaster** [comment]
Will look into default export.

**Comment by Dexmaster** [comment]
Fixed readme, we use 'named' exports in rollup. It's better for tree-shaking and makes code more readable.
