### ISSUE TITLE
Illegal argument error needs to be more descriptive

### ISSUE THREAD

**Issue by douglasg14b** [tomitribe/jwt-js-decode#5]
This error started happening out of the blue to users due to a bad server response causing the JWT passed into `jwtDecode()` to not be a string.

The cryptic error `Illegal argument specified!` was almost maliciously unhelpful...

**Comment by Dexmaster** [comment]
Hello, do you have a proposal about how to improve error message?
Illegal JWT passed? JWT is invalid?

**Comment by douglasg14b** [comment]
Error messages should relay information to the dev that describes where, what, why. Not necessarily the internal location either, but ideally where the dev made the call that caused the error. 

A first-pass error message could look like:

> Invalid JWT passed to `__Location of Error__`. Expected string, received `__type & value received__`

**Comment by Dexmaster** [comment]
Ok, I will partially use your proposal. I feel we should not provide full value, as it's not a debug statement. For debugging this you should use `DevTools -> Pause on exceptions` and check `Scope`. 

Here is version I feel is best for this improvement. If you don't like this solution (have a better one), we can discuss it here or on PR.
>Invalid argument passed to `__callee function__`. 
`<case type !== 'string'>` Expected type 'string', received '`__typeof argument__`'.
`<case length === 0>` Provided JWT string is empty.
`<default>` Provided JWT string is invalid.

**Comment by Dexmaster** [comment]
Published 1.4.1 with mentioned changes. If no further discussion will be provided will close this ticket in a week.

**Comment by Dexmaster** [comment]
Hope changes are to your liking. Feel free to open new tickets if you find any bugs or enhancements. Closing this one.

**Comment by douglasg14b** [comment]
Looks great to me! The goal was to make it less obfuscated for others, I already know what the error is at this point :+1:
